steps:
  author-header:
    image: codeberg.org/qwerty287/woodpecker-regex-check
    settings:
      pattern: "*.java"
      regex: " \\\\* \\\\@author [\\\\S\\\\s]+"
      must_contain: true
    when:
      event: [ push ]
      path: [ app/**, build.gradle ]

  style:
    image: alvrme/alpine-android:android-34-jdk21
    commands:
      - ./gradlew :app:spotlessCheck
    when:
      event: [ push ]
      path: [ app/**, build.gradle ]

  test:
    image: alvrme/alpine-android:android-34-jdk21
    commands:
      - ./gradlew test
    when:
      event: [ push ]
      path: [ app/**, build.gradle ]
